name: Deploy to Staging (CI + EAS Update)

on:
  push:
    branches: [ "develop" ]

concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI (typecheck/lint/tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - name: Typecheck
        run: npm run --if-present typecheck

      - name: Lint
        run: npm run --if-present lint

      - name: Tests
        run: |
          npm run --if-present test:ci || npm run --if-present test -- --run

  update:
    name: Publish update to staging channel
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - uses: expo/expo-github-action@8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - run: npm ci

      - name: Expo doctor (non-blocking)
        run: CI=1 npx expo-doctor || true

      - name: Publish OTA update to staging
        run: |
          eas --version
          eas update --non-interactive \
            --channel staging \
            --message "staging @ $GITHUB_SHA"
